# Generated by Django 5.1.7 on 2025-03-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectmilestone_is_funded_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmilestone',
            name='is_funded',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
