# Generated by Django 5.1.7 on 2025-04-07 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmilestone',
            name='max_penalty_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='max_penalty_percentage',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='penalty_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delayed', 'Delayed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='MilestoneDelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_days', models.IntegerField(default=0)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='core.projectmilestone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
