apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: jayasurya88/freelenso-notification-service:latest
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:postgres@notification-db:5432/notification_service
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort 