apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-db
  template:
    metadata:
      labels:
        app: project-db
    spec:
      containers:
      - name: project-db
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: project_service
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: project-db-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: project-db-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: project-db
spec:
  selector:
    app: project-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP 